name: Packer Pipeline for AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  packer:
    runs-on: self-hosted  

    env:
      PACKER_LOG: 1  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up HashiCorp Packer
        uses: hashicorp/setup-packer@v2

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Configure AWS CLI with credentials
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Initialize Packer template
        run: packer init .

      - name: Validate Packer template
        run: |
          packer validate -var-file=values.pkrvars.hcl .

      - name: Build Packer Image
        run: |
          packer build -var-file=values.pkrvars.hcl .

      - name: Notify success
        if: success()
        run: echo "Packer image build successful!"

      - name: Notify failure
        if: failure()
        run: echo "Packer image build failed."
